### ISSUE TITLE
After Successful Sign, DNN Shows Not Signed In

### ISSUE THREAD

**Issue by iconITguy** [davidjrh/dnn.azureadprovider#10]
I've followed the instructions and when I attempt to login with Azure, I'm sent to the Azure AD sign-in page, I successfully sign in and am redirected back to DNN but in DNN, I'm not actually signed in as far as the UI goes.  If I check the log in DNN, it shows a successful login by the Azure user account.  Any idea what I'm missing in the setup or what is wrong?

Thanks!

**Comment by mryckman** [comment]
I'm having this same problem... any luck figuring it out?

**Comment by shanewalker1595** [comment]
Did you authorize the azure account?

**Comment by iconITguy** [comment]
That's strange.  I thought for sure I had authorized the account on one of my test runs but trying it again, it seems to be working now.  Thanks!
