### ISSUE TITLE
Settings do not save in DNN 9.01+

### ISSUE THREAD

**Issue by shanewalker1595** [davidjrh/dnn.azureadprovider#12]
When configuring settings in DNN 9.01+, the settings will not save. Manually creating them in the Database works though.

Status Code: 404
URL: /API/personaBar/AzureAD/UpdateSettings

**Comment by davidjrh** [comment]
Hi @shanewalker1595, I'm running a 9.1.1 and can't reproduce the issue. Can you confirm this is still a problem?

**Comment by shanewalker1595** [comment]
The issue seems to be resolved in DNN 9.1.1

**Comment by davidjrh** [comment]
Ok, closing the issue
