### ISSUE TITLE
Automatically Authorize?

### ISSUE THREAD

**Issue by mryckman** [davidjrh/dnn.azureadprovider#14]
From a different issue, I saw the problem with users not being authorized when they first sign in. This certainly created a confusing experience for me, and I'm sure others. Also, it adds a lot of administrative work.

Is there a way to automatically authorize new Azure users?

**Comment by davidjrh** [comment]
You just need to change the setting "Settings > Security > Member Accounts > Registration Settings > User Registration" from "Verified" to another one that best suits your needs. 

Let me know if that solves your issue.

**Comment by davidjrh** [comment]
On v4.0.0 version, a new implementation now allows to automatically authorize the user without the need to set the User Registration to verified. 
https://github.com/davidjrh/dnn.azureadprovider/releases/tag/v4.0.0-preview

**Comment by rodsmr** [comment]
Hi @davidjrh , thanks for your work!
Is there a way to avoid automatically authorize without change user registration?
Thanks

**Comment by davidjrh** [comment]
Sounds like a new setting: "Automatically authorize users after login" (Yes/No), to enable/disable this behavior, right? I'm doing some new modifications on the Provider for a new release before the end of the year, and I can add this request.

**Comment by rodsmr** [comment]
> Sounds like a new setting: "Automatically authorize users after login" (Yes/No), to enable/disable this behavior, right? I'm doing some new modifications on the Provider for a new release before the end of the year, and I can add this request.

Correct, thanks a lot!

**Comment by davidjrh** [comment]
Added the setting to enable/disable automatic authorization after login
