### ISSUE TITLE
Setup for DNN 7.4.1

### ISSUE THREAD

**Issue by vmasanas** [davidjrh/dnn.azureadprovider#18]
I'm trying to configure v1 on a DNN 7.4.1 and the settings contain a few extra options not mentioned here.
So far I see:
- TokenEndPointId
- AuthorizationEndPoint
- GraphEndPoint
- AppIdUri
- APIKey
- APISecret

I have the following params for my account: Directory ID, AppID and key. 
I guess tha Key referst to APISecret but don't know how to configure everything else.

Anyone?

**Comment by davidjrh** [comment]
Closing as old issue, and it is already documented.
