### ISSUE TITLE
Multi tenant sign in

### ISSUE THREAD

**Issue by iiminov** [davidjrh/dnn.azureadprovider#2]
I ran into a problem signing in users when I tried to leverage multi tenant configuration in Azure AD.

I can still sing in users from my original tenant where I created my App/API without any issues. But as soon as I try to signin with a user from any other tenant I run into a problem.

```
RawUrl:/Login?code=AAABAAAAiL9Kn2Z27UubvWFPbm0gLUu25ZYGjYBi5qRj0Gm4O7mMLuKLs5bAgBgyjqDFj-hhjHACeXaJmYwIx7B25GzvKKLvhuehMzLVEFd50uj7o45GpO0EXgBNlQEp1tVbiuAnRY8VtNHM1VbUdxZ-fU8db_dQMwecibxU0UQNMyagVFhv--3Tbe7_MTC0oon9Z2t6CM5FGvX3yTuL9x92x6OR1__OYat47FR2_MgyslUFpDrcoWn7
Message:There was an error processing the credentials. Contact your system administrator.
InnerStackTrace:
   at DotNetNuke.Authentication.Azure.Components.AzureClient.GetToken(String responseText)
   at DotNetNuke.Services.Authentication.OAuth.OAuthClientBase.ExchangeCodeForToken()
   at DotNetNuke.Services.Authentication.OAuth.OAuthClientBase.AuthorizeV2()
   at DotNetNuke.Services.Authentication.OAuth.OAuthLoginBase.OnLoad(EventArgs e)
   ...
```

Looking at `AzureClient.GetToken` the exception is thrown when `responseText` is either null or an empty string. And the method seems simple enough too.

I looked over `OAuthClientBase.AuthorizeV2` and `OAuthClientBase.ExchangeCodeForToken` but nothing jumped out at me.

Do you have any plans to allow for multi tenant scenarios?
Or is it even possible?

**Comment by davidjrh** [comment]
Ricardo Leon is going to commit a change with some new additions, including a new scheduled task that syncs AD Roles and role members. 

There is also a specific fix for the error you are mentioning: when an AD authenticated user has no permissions to the Application you created on the Azure portal. You can add users from other tenants to an existing tenant, and then give permissions to the Application (the "trust" could be done via Azure AD).

**Comment by iiminov** [comment]
> @davidjrh 
As a workaround, you can add users from other tenants to an existing tenant, and then give permissions to the Application

Thank you for the info. That certainly gives me another option. I believe I read something about it somewhere in [here](https://azure.microsoft.com/en-us/documentation/services/active-directory/) a while back.
