### ISSUE TITLE
Saving Secrets While Not Logged In

### ISSUE THREAD

**Issue by ahoefling** [davidjrh/dnn.azureadprovider#23]
# Scenario
As a host user I have logged in and opened the Persona Bar Module to configure Azure AD. My session expires and I attempt a save and no error appears.

# Reproduction Steps
1. Install Module into new instance of DNN
2. Configure Azure AD correctly per the documentation
3. open a new tab
4. log out and verify that you are logged out in new tab
5. in the original tab update the Azure AD secrets/appid or directory id

## Expected Behavior
* A warning message or something should notify the user they are not actually logged in

## Actual Behavior
* The UI appears to process without issue
* The backend does not save the new credentials

# Notes/Comments
It appears this works as designed, but the front-end of the Persona Bar module doesn't get a good communication with the backend, which makes sense you are no longer logged in and the session has expired. 

It would be a nice polish to add an error message on the Persona Bar module if the front-end code can't communicate with the API

# Versions
DNN: 9.4.1
Module: 3.1.0

# Other
This module is really great! I built custom Azure AD Providers for customers before and I was very impressed this just worked out of the box. I am really glad I found this and you guys did a great job from the UI/UX. Any Admin that is familiar with the Azure AD side shouldn't have a problem configuring this.

Great Job!

**Comment by davidjrh** [comment]
Thanks @ahoefling, this situation should be handled on the personaBar React component. I have added it to the backlog.

**Comment by gbulicanu** [comment]
@davidjrh please have a look
