### ISSUE TITLE
Error updating settings

### ISSUE THREAD

**Issue by mnagatos101** [davidjrh/dnn.azureadprovider#26]
We are are on DNN 9.5.  This error triggers when updating the settings.  Please advise.

![Capture](https://user-images.githubusercontent.com/35544902/79026023-5dca1380-7b3c-11ea-8122-7796a55e093e.PNG)

**Comment by davidjrh** [comment]
Which version of the module? 4.0?

**Comment by mnagatos101** [comment]
Yes, we are on version 4.0.

**Comment by MarkJaroski** [comment]
Is there a workaround for this, by chance?

**Comment by MarkJaroski** [comment]
Ah, I found a workaround. I changed the call to updateGenericSettings() in export-bundle.js.

**Comment by moorecreative** [comment]
I can confirm the same issue in DNN 9.5 and encounter it not saving in module version 3x and 4x.

What was the edit that Mark made to workaround? was it an edit in the module references? or was it in the personabar js of DNN 9.5?

**Comment by davidjrh** [comment]
Going to check this

**Comment by davidjrh** [comment]
Fixed con commit f392f73

**Comment by moorecreative** [comment]
I am not sure if this is related or a side product of the update still having an issue. I have made a test of saving settings in DNN 9.5, Module version 4.0.1 and receive this error regarding the bundle-en.js.map 404 and js error

![image](https://user-images.githubusercontent.com/5497943/82096642-582d9380-96cf-11ea-9dcb-30b947e501fa.png)

**Comment by moorecreative** [comment]
@davidjrh  ^^

**Comment by davidjrh** [comment]
Please ensure you are not using the previous cached version of the .js file

**Comment by moorecreative** [comment]
YES, that was 100% the issue, you're right. Force clearing cache and or running from a different browser and it saved settings successfully.

super thanks!
