### ISSUE TITLE
Error in Role Sync Job

### ISSUE THREAD

**Issue by mnagatos101** [davidjrh/dnn.azureadprovider#27]
It says it succeeded, but this exception kicks and the roles do not pull down to DNN.

Starting Azure AD Synchronization Error while synchronizing the roles from portal 0: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=5.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=5.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' at DotNetNuke.Authentication.Azure.Components.Graph.GraphClient..ctor(String clientId, String clientSecret, String tenant) at DotNetNuke.Authentication.Azure.ScheduledTasks.SyncSchedule.SyncRoles(Int32 portalId, AzureConfig settings) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]. Azure AD Synchronization finished successfully

**Comment by davidjrh** [comment]
By your message in the other thread, I suppose you are using DNN 9.5. Going to test this with the latest 9.6.1 version and see if there is a missing binding redirect or is just the assembly not being included in the package.

**Comment by davidjrh** [comment]
Fixed on commit 9f57c7ba4cc1bdde15472344c8dd997227077b3f
