### ISSUE TITLE
newest version number is 4x or 5x?

### ISSUE THREAD

**Issue by moorecreative** [davidjrh/dnn.azureadprovider#29]
Within the DNN Extensions screen, the column for version upgrade shows that there is a newer version number out for the authentication provider (see screenshot). Is that a mistake in the version number listed?

![image](https://user-images.githubusercontent.com/5497943/81870436-d3623e80-9543-11ea-91f4-34313425ad69.png)

**Comment by davidjrh** [comment]
Sounds like a bug in DNN Platform. Latest version at this moment is 4.0.0

**Comment by davidjrh** [comment]
I'm seeing this below, so I suppose was a transient failure on the update feed from DNN Platform. I'm going to close it, if you see it again, let me know to re-open and investigate this deeply. 

![image](https://user-images.githubusercontent.com/489976/85944555-825dac80-b92f-11ea-9ed1-2c910eaf9de5.png)

**Comment by rodsmr** [comment]
Hi @davidjrh , this is my situation:
![tempsnip](https://user-images.githubusercontent.com/17640209/111131139-39f72500-8578-11eb-9a34-f362c9708824.png)

Do you need other info?
Thanks :)
