### ISSUE TITLE
Can't assign permissions to Azure AD users until they login for the first time

### ISSUE THREAD

**Issue by davidjrh** [davidjrh/dnn.azureadprovider#34]
Currently there is no way to give user specific permissions to Azure AD users until they login at least for the first time. While there is a scheduled role sync implemented, there is no scheduled user sync so users automatically populates on DNN. 

Would be nice to have a scheduled task that synchronizes Azure AD users in background every X hours by using the MS Graph API with filter support to avoid fully synchronizing huge Azure AD tenants.

**Comment by JRPonte** [comment]
Hi David, I have your module on a production portal.
I'll like to assign an user role to every user that authenticate with AAD. So the user may not have been previously created on DNN, the creation of the new user should be with the first login and automatically assign a role. 
Is this possible?

**Comment by davidjrh** [comment]
Solved the implementation of the user sync on v4.2.0
