### ISSUE TITLE
Redirect Uri validation

### ISSUE THREAD

**Issue by trouble2** [davidjrh/dnn.azureadprovider#37]
In the previously installed version, the provider seemed to work, however, it redirected me back to the login page, and the login page redirected me back to Azure, so I ended up in an endless loop. So I decided to install the new version, since this has the Redirect URI field, which should redirect me to another page instead of the login page.

I just entered "/" into the Redirect URI, so my expectation was that it would redirect to the homepage.
The result was that the login page gave me an error and I basically could not login anymore.
So please add some validation and some help text that you should enter the full url...

**Comment by davidjrh** [comment]
Gotcha. Sounds like an easy validation check, and will add the help text. Thanks for the feedback!

**Comment by davidjrh** [comment]
This has been fixed on PR #64
