### ISSUE TITLE
Pass user profile data to third party API

### ISSUE THREAD

**Issue by maduranga001** [davidjrh/dnn.azureadprovider#42]
Please, can I know if it is possible to pass DNN user profile data to another Web API through this module? It may be query string or though tokens or any other possible way to pass the data to a third-party external app?

I appreciate your support.

**Comment by davidjrh** [comment]
The token can be used to authenticate on another Web API, but some advanced settings must be setup. Please check the documentation available for the B2C module that would apply on this case:
* https://github.com/intelequia/dnn.azureadb2cprovider
* https://github.com/intelequia/dnn.azureadb2cprovider#samples
