### ISSUE TITLE
Private registration but user automatically authorized

### ISSUE THREAD

**Issue by rodsmr** [davidjrh/dnn.azureadprovider#43]
**Environment**
- DNN 9.9.0
- DNN Azure AD Provider 4.3.0
- Windows Server 2012 R2

**Problems**
I set private registration (how described in [DNN registration type](https://www.dnnsoftware.com/wiki/registration-types)): I think a not registered AD users need to be authorized by Site Admin but this does't happen.
I'm going to explain my problem

1. A not registered AD user try to "Sign in with Azure":
    1. a new user will be created
    2. not registered user receive, on the screen, the message
    > An e-mail with your details has been sent to the Site Administrator for verification. You will be notified by email when your registration has been approved.
2. Site Administrator doesn't receive mail
3. Not registered AD user (now it's registered) try again to "Sign in with Azure" and can access to the site

Why does it happen?
Thanks for the support

**Comment by davidjrh** [comment]
This scenario was fixed on commit https://github.com/davidjrh/dnn.azureadprovider/commit/acd6242edd0da59ddda1064615c5747dde0a63ea and a new setting was introduced to disable the "Automatic authorization" of users after signing in (is enabled by default since you can control that behavior through the Azure AD app configuration). 

I will try to build a new release this week to include that behavior.

**Comment by rodsmr** [comment]
> This scenario was fixed on commit [acd6242](https://github.com/davidjrh/dnn.azureadprovider/commit/acd6242edd0da59ddda1064615c5747dde0a63ea) and a new setting was introduced to disable the "Automatic authorization" of users after signing in (is enabled by default since you can control that behavior through the Azure AD app configuration).
> 
> I will try to build a new release this week to include that behavior.

Hi @davidjrh , is there update about new release?
Thanks for your work :)

**Comment by davidjrh** [comment]
Hi @rodsmr , the new v4.0.4 has been released including the new setting. Hope this helps!
