### ISSUE TITLE
ADAL deprecation

### ISSUE THREAD

**Issue by jeestirlingdev** [davidjrh/dnn.azureadprovider#49]
From a quick look at the code it looks like this provider is using Azure Active Directory Authentication Library (ADAL). Microsoft is deprecating ADAL with support ending June 2022 and recommending apps migrate to Microsoft Authentication Library (MSAL).

If it is the case that the provider is using ADAL, are there plans to migrate to MSAL? We have some development capacity but do not wwant to duplicate effort if this is already in hand.

**Comment by davidjrh** [comment]
Hi @jeestirlingdev! We'are actively working on it now, and expecting to have it ready for tests before the end of October, for this provider and for the Azure AD B2C provider as well.

**Comment by jeestirlingdev** [comment]
Excellent! We will watch out for testing releases and give feedback asap. Let me know if we can help out in other ways.
