### ISSUE TITLE
Error when upgrading to DNN Evoq 9.10

### ISSUE THREAD

**Issue by pmmarkley** [davidjrh/dnn.azureadprovider#60]
I recently upgraded our development environment to DNN version 9.10 and after I receive the following error when navigating to the login screen:

System.TypeLoadException: Could not load type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' from assembly 'System.IdentityModel.Tokens.Jwt, Version=4.0.20622.1351, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
![Screen Shot 2022-07-20 at 3 12 22 PM](https://user-images.githubusercontent.com/52170884/180063545-c8e8c68b-6c4d-4b3b-b554-7008b6a0921f.png)
.

**Comment by pmmarkley** [comment]
I did try the work around linked below but it did not work. I still receive the same error.

https://github.com/davidjrh/dnn.azureadprovider/issues/38

**Comment by davidjrh** [comment]
Hi @pmmarkley, that error should be solved following instructions described on #38, just replace the `newVersion="5.6.0.0"` with the version of your library.

**Comment by pmmarkley** [comment]
Hi @davidjrh, 

That version is already in the web.config as the new version
![Screen Shot 2022-07-20 at 4 25 50 PM](https://user-images.githubusercontent.com/52170884/180075127-b441a252-dd0e-42af-9db5-8759284a9e06.png)
.

**Comment by davidjrh** [comment]
Which version of the Azure AD module was previously installed? 

I'm sorry I don't have access to a Evoq version to test it with that version. Sounds like Evoq is using an old version of that library and changed the version needed by the Azure AD module or any of its dependencies. Have you opened a support ticket to DNN Corp.? Since it is an Evoq version, they should be able to fix this for you.

**Comment by pmmarkley** [comment]
Ok thank you for your help.

Thank you,

Pamela Markley
Web Development Manager
Department of Information Technology
Columbus Consolidated Government


From: David Rodríguez ***@***.***>
Date: Wednesday, July 20, 2022 at 4:47 PM
To: davidjrh/dnn.azureadprovider ***@***.***>
Cc: Pamela Markley ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [davidjrh/dnn.azureadprovider] Error when upgrading to DNN Evoq 9.10 (Issue #60)

Which version of the Azure AD module was previously installed?

I'm sorry I don't have access to a Evoq version to test it with that version. Sounds like Evoq is using an old version of that library and changed the version needed by the Azure AD module or any of its dependencies. Have you opened a support ticket to DNN Corp.? Since it is an Evoq version, they should be able to fix this for you.
