### ISSUE TITLE
Acceso con usuario local (admin)

### ISSUE THREAD

**Issue by peya02** [davidjrh/dnn.azureadprovider#63]
Hola @davidjrh 
He implantado la versión AzureADProvider 4_1_1 y accedo perfectamente con cualquier usuario de mi azure, el problema es que no sé cómo puedo acceder ahora con el usuario local creado al inicio del host, básicamente este usuario es el superadmin y con los que accedo de Azure no pueden hacer nada. 
¿hay forma de acceder con usuario local o asignar permisos admin algún usuario de azure?
Gracias.

**Comment by davidjrh** [comment]
Hola @peya02, 

si has habilitado la opción de autoredirección, no se muestra la pantalla de login de DNN y que permite seleccionar el proveedor de identidad. Si quieres forzar a que te aparezca esa pantalla y así hacer login con el usuario de DNN, puedes usar la URL ./Login?legacy=true

Así entras con tu usuario superadmin, y puedes hacer superadmin a otros usuarios de Azure AD sin problemas.

**Comment by peya02** [comment]
Hola @davidjrh 
si accedo a https://powerbi.dnndev.me/Login?legacy=true me redirige igualmente a login de O365.

**Comment by davidjrh** [comment]
Perdón, fallo mío, usa esta: https://powerbi.dnndev.me/Login?legacy=1

**Comment by peya02** [comment]
Hola @davidjrh 
Ahora si, muchas gracias.
