### ISSUE TITLE
How can we change the text from "Sign In with Azure"

### ISSUE THREAD

**Issue by shanewalker1595** [davidjrh/dnn.azureadprovider#8]
Is this something that we could add to be a module setting? I would be willing to work on this myself.

**Comment by davidjrh** [comment]
Currently there is no setting to configure the text, other than just editing the resx file https://github.com/davidjrh/dnn.azureadprovider/blob/master/DotNetNuke.Authentication.Azure/App_LocalResources/Login.ascx.resx
