### ISSUE TITLE
Apply settings global, not on a portal-by-portal basis?

### ISSUE THREAD

**Issue by shanewalker1595** [davidjrh/dnn.azureadprovider#9]
As it currently stands, the settings can only be used on a portal-by-portal basis. The extension must be configured for each portal.

How Can I apply these settings globally?

**Comment by davidjrh** [comment]
Hi, the settings must be applied by portal because is how DNN auth works. Perhaps you want to check the DNN site groups feature? It allows to use the same users/roles for a group of portals.

**Comment by davidjrh** [comment]
Hi, on the Azure AD B2C provider (https://github.com/intelequia/dnn.azureadb2cprovider) I recently implemented the global settings feature, and I now understand better this request. Adding it to the backlog.

**Comment by davidjrh** [comment]
This is now implemented on v4.0 https://github.com/davidjrh/dnn.azureadprovider/releases/tag/v4.0.0-preview
