### ISSUE TITLE
node_modules directory included in _Install.zip package

### ISSUE THREAD

**Issue by RichFinn-WTW** [davidjrh/dnn.azureadprovider#92]
Hi - I noticed that your `node_modules` directory from the react app is being included in the install package and being output at  `\DesktopModules\AuthenticationServices\Azure\AzureAD.Web`

![image](https://github.com/davidjrh/dnn.azureadprovider/assets/12137272/57037180-a29a-4ec1-a4c3-78f470a014da)

This is adding 1.2MB of unpacked files to the host. I'm thinking it's because of this line in `.build/ModulePackage.targets:22`:

```xml
<InstallInclude Include="**\*.txt;**\*.ascx;**\*.css"  Exclude="**\obj\**;**\_ReSharper*\**;packages\**;" />
```

I also noticed that the `packages` directory is being included, even though it looks like you want it to be excluded in the line above.

![image](https://github.com/davidjrh/dnn.azureadprovider/assets/12137272/d8d62e4c-c7d0-4dcf-ab5f-90cf0ee66a83)

Changing to the following might help:

```xml
<InstallInclude Include="**\*.txt;**\*.ascx;**\*.css"  Exclude="**\obj\**;**\_ReSharper*\**;**\packages\**;**\node_modules\**;" />
```

**Comment by davidjrh** [comment]
Thanks for reporting it! @alendv fixed it on #101
